In [1]:
import numpy as np

In [3]:
np.array((1,3))

array([1, 3])

In [8]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
a=np.array((1,10))

In [11]:
a

array([ 1, 10])

In [12]:
a.mean

<function ndarray.mean>

In [13]:
a.argmin

<function ndarray.argmin>

In [15]:
np.arange(0,101,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [16]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.linspace(0,11,13)

array([ 0.        ,  0.91666667,  1.83333333,  2.75      ,  3.66666667,
        4.58333333,  5.5       ,  6.41666667,  7.33333333,  8.25      ,
        9.16666667, 10.08333333, 11.        ])

In [23]:
num=np.linspace(4000,8000,800)

num


In [24]:
print(num)

[4000.         4005.00625782 4010.01251564 4015.01877347 4020.02503129
 4025.03128911 4030.03754693 4035.04380476 4040.05006258 4045.0563204
 4050.06257822 4055.06883605 4060.07509387 4065.08135169 4070.08760951
 4075.09386733 4080.10012516 4085.10638298 4090.1126408  4095.11889862
 4100.12515645 4105.13141427 4110.13767209 4115.14392991 4120.15018773
 4125.15644556 4130.16270338 4135.1689612  4140.17521902 4145.18147685
 4150.18773467 4155.19399249 4160.20025031 4165.20650814 4170.21276596
 4175.21902378 4180.2252816  4185.23153942 4190.23779725 4195.24405507
 4200.25031289 4205.25657071 4210.26282854 4215.26908636 4220.27534418
 4225.281602   4230.28785982 4235.29411765 4240.30037547 4245.30663329
 4250.31289111 4255.31914894 4260.32540676 4265.33166458 4270.3379224
 4275.34418023 4280.35043805 4285.35669587 4290.36295369 4295.36921151
 4300.37546934 4305.38172716 4310.38798498 4315.3942428  4320.40050063
 4325.40675845 4330.41301627 4335.41927409 4340.42553191 4345.43178974
 4350.43

In [25]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [26]:
np.arange(4000,8000,40)

array([4000, 4040, 4080, 4120, 4160, 4200, 4240, 4280, 4320, 4360, 4400,
       4440, 4480, 4520, 4560, 4600, 4640, 4680, 4720, 4760, 4800, 4840,
       4880, 4920, 4960, 5000, 5040, 5080, 5120, 5160, 5200, 5240, 5280,
       5320, 5360, 5400, 5440, 5480, 5520, 5560, 5600, 5640, 5680, 5720,
       5760, 5800, 5840, 5880, 5920, 5960, 6000, 6040, 6080, 6120, 6160,
       6200, 6240, 6280, 6320, 6360, 6400, 6440, 6480, 6520, 6560, 6600,
       6640, 6680, 6720, 6760, 6800, 6840, 6880, 6920, 6960, 7000, 7040,
       7080, 7120, 7160, 7200, 7240, 7280, 7320, 7360, 7400, 7440, 7480,
       7520, 7560, 7600, 7640, 7680, 7720, 7760, 7800, 7840, 7880, 7920,
       7960])

In [28]:
np.random.randint (0,100,10)

array([82, 52, 40, 87, 55, 19, 48, 11, 24, 67])

In [29]:
np.random.randint(10,400,(2,2))

array([[288, 306],
       [320,  73]])

In [31]:
np.random.randint(10,400,(5,5))

array([[170, 313,  82, 274,  17],
       [ 31, 277, 182, 232, 309],
       [ 72, 398, 277, 330, 298],
       [376, 340, 247, 276,  48],
       [217, 112, 392, 300, 279]])

In [34]:
np.random.seed(5)
np.random.randint(0,10,7)

array([3, 6, 6, 0, 9, 8, 4])

In [35]:
np.random.seed(5)
np.random.randint(0,10,7)

array([3, 6, 6, 0, 9, 8, 4])

In [37]:
mat=np.arange(0,100)

In [38]:
print(mat)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [40]:
mat.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [43]:
A=mat.reshape(10,10)

In [44]:
print(A)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [45]:

A.argmax()

99

In [46]:
A.argmin()

0

In [48]:
A.mean()

49.5

In [49]:

A[0,5]

5

In [50]:
A[5,8]

58

In [51]:
A[:,6]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [52]:
A[7,:]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [54]:
A[1:4,7:9]

array([[17, 18],
       [27, 28],
       [37, 38]])

In [55]:
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [56]:

A>40

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [57]:
print(A>40)

[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


In [58]:
A[A>70]

array([71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])